// themes.js — Central theme registry for Lumea
// Each theme defines CSS variable overrides + theme-specific copy text.

export const THEMES = {
  none: {
    id: 'none',
    label: 'None',
    description: 'Standard UI',
    icon: '☀️',
    swatchGradient: 'linear-gradient(135deg, #e2e8f0, #cbd5e1)',
    // CSS variable overrides applied to [data-theme="none"]
    cssVars: {
      '--background': '#f8fafc',
      '--bg-gradient': 'linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%)',
      '--foreground': '#0f172a',
      '--muted': '#334155',
      '--glass-bg': 'rgba(255, 255, 255, 0.75)',
      '--glass-border': 'rgba(0, 0, 0, 0.12)',
      '--primary': '#6366f1',
      '--secondary': '#8b5cf6',
      '--primary-glow': 'rgba(99, 102, 241, 0.2)',
      '--canvas-bg': '#f1f5f9',
      '--glass-shadow': '0 10px 30px rgba(0, 0, 0, 0.08)',
    },
    // Theme-specific JS color tokens (mirrors theme.js)
    colors: {
      primary: '#6366f1',
      primaryContainer: '#4338ca',
      secondary: '#8b5cf6',
      accent: '#7c3aed',
      foreground: '#0f172a',
      muted: '#334155',
      glass: 'rgba(255, 255, 255, 0.7)',
      glassBorder: 'rgba(0, 0, 0, 0.07)',
      glow: 'rgba(99, 102, 241, 0.3)',
      surface: '#e2e8f0',
    },
    // Copy text
    copy: {
      heroHeadline: 'Find Your\nInner Calm.',
      heroTagline: 'Meet Lumea — a calm, clear space to think, feel, and breathe. Simple tools, thoughtful design.',
      heroCTA: 'Get Started',
      dashboardGreetingSuffix: 'Your space is bright and ready.',
      quote: '"Simplicity is the ultimate sophistication."',
      quoteSource: 'Daily Reflection',
      aiGreeter: "Hello! I'm Lumea, here to listen and support you. What's on your mind today?",
      journalPlaceholder: 'Write freely. This space is yours.',
      noJournalText: 'No reflections yet. Begin writing your first entry.',
      moodTitle: 'Dashboard',
      moodSubtitle: 'Your emotional landscape at a glance.',
    },
  },

  dark: {
    id: 'dark',
    label: 'Dark',
    description: 'Standard Dark',
    icon: '🌑',
    swatchGradient: 'linear-gradient(135deg, #1e293b, #0f172a)',
    cssVars: {
      '--background': '#09090b',
      '--bg-gradient': 'linear-gradient(135deg, #09090b 0%, #18181b 100%)',
      '--foreground': '#fafafa',
      '--muted': '#a1a1aa',
      '--glass-bg': 'rgba(24, 24, 27, 0.6)',
      '--glass-border': 'rgba(255, 255, 255, 0.06)',
      '--primary': '#d4d4d8',
      '--secondary': '#a1a1aa',
      '--primary-glow': 'rgba(212, 212, 216, 0.15)',
      '--canvas-bg': '#09090b',
      '--glass-shadow': '0 20px 50px rgba(0, 0, 0, 0.5)',
    },
    colors: {
      primary: '#d4d4d8',
      primaryContainer: '#3f3f46',
      secondary: '#a1a1aa',
      accent: '#e4e4e7',
      foreground: '#fafafa',
      muted: '#71717a',
      glass: 'rgba(24, 24, 27, 0.6)',
      glassBorder: 'rgba(255, 255, 255, 0.06)',
      glow: 'rgba(212, 212, 216, 0.2)',
      surface: '#18181b',
    },
    copy: {
      heroHeadline: 'Quiet the\nNoise Inside.',
      heroTagline: 'Lumea is your private corner of the internet — dark, calm, and without distraction.',
      heroCTA: 'Enter the Quiet',
      dashboardGreetingSuffix: 'The quiet is yours tonight.',
      quote: '"In the depth of winter, I finally learned that within me there lay an invincible summer."',
      quoteSource: 'Midnight Thought',
      aiGreeter: "The night is quiet and I'm all yours. What would you like to explore?",
      journalPlaceholder: 'Let the darkness hold your words safely...',
      noJournalText: 'No entries yet. The page is dark and waiting for your light.',
      moodTitle: 'Dashboard',
      moodSubtitle: 'How are the tides moving beneath the surface?',
    },
  },

  desert: {
    id: 'desert',
    label: 'Desert',
    description: 'Desert Vibes',
    icon: '🏜️',
    swatchGradient: 'linear-gradient(135deg, #d97706, #92400e)',
    cssVars: {
      '--background': '#1c0f05',
      '--bg-gradient': 'linear-gradient(135deg, #1c0f05 0%, #2d1a0a 50%, #3b1f0a 100%)',
      '--foreground': '#fef3c7',
      '--muted': '#a78b6a',
      '--glass-bg': 'rgba(42, 22, 8, 0.55)',
      '--glass-border': 'rgba(251, 191, 36, 0.12)',
      '--primary': '#f59e0b',
      '--secondary': '#d97706',
      '--primary-glow': 'rgba(245, 158, 11, 0.3)',
      '--canvas-bg': '#1c0f05',
      '--glass-shadow': '0 20px 50px rgba(0, 0, 0, 0.5)',
    },
    colors: {
      primary: '#f59e0b',
      primaryContainer: '#92400e',
      secondary: '#d97706',
      accent: '#fbbf24',
      foreground: '#fef3c7',
      muted: '#a78b6a',
      glass: 'rgba(42, 22, 8, 0.55)',
      glassBorder: 'rgba(251, 191, 36, 0.12)',
      glow: 'rgba(245, 158, 11, 0.4)',
      surface: '#2d1a0a',
    },
    copy: {
      heroHeadline: 'Wander Into\nYour Own Desert.',
      heroTagline: 'Like the desert dawn — vast, warm, and full of unexpected beauty. Lumea walks beside you.',
      heroCTA: 'Begin the Journey',
      dashboardGreetingSuffix: 'The desert sun rises for you.',
      quote: '"Not all who wander are lost — some are finding themselves in the open dunes."',
      quoteSource: 'Desert Wisdom',
      aiGreeter: 'Welcome, wanderer. The desert is patient and so am I. What weighs on your mind?',
      journalPlaceholder: 'Write your desert trail here — every step matters...',
      noJournalText: 'The dunes are empty. Leave your first footprint.',
      moodTitle: 'Dashboard',
      moodSubtitle: 'How does the wind blow within you today?',
    },
  },

  ocean: {
    id: 'ocean',
    label: 'Ocean',
    description: 'Sea & Ocean Vibes',
    icon: '🌊',
    swatchGradient: 'linear-gradient(135deg, #0e7490, #164e63)',
    cssVars: {
      '--background': '#020c14',
      '--bg-gradient': 'linear-gradient(135deg, #020c14 0%, #0c2233 50%, #0e3d52 100%)',
      '--foreground': '#e0f2fe',
      '--muted': '#67a9c5',
      '--glass-bg': 'rgba(6, 28, 46, 0.55)',
      '--glass-border': 'rgba(103, 232, 249, 0.1)',
      '--primary': '#22d3ee',
      '--secondary': '#0891b2',
      '--primary-glow': 'rgba(34, 211, 238, 0.3)',
      '--canvas-bg': '#020c14',
      '--glass-shadow': '0 20px 50px rgba(0, 0, 0, 0.5)',
    },
    colors: {
      primary: '#22d3ee',
      primaryContainer: '#0e7490',
      secondary: '#06b6d4',
      accent: '#67e8f9',
      foreground: '#e0f2fe',
      muted: '#67a9c5',
      glass: 'rgba(6, 28, 46, 0.55)',
      glassBorder: 'rgba(103, 232, 249, 0.1)',
      glow: 'rgba(34, 211, 238, 0.4)',
      surface: '#0c2233',
    },
    copy: {
      heroHeadline: 'Dive Into\nYour Depths.',
      heroTagline: 'Like the ocean — your emotions have layers, tides, and hidden beauty. Lumea dives with you.',
      heroCTA: 'Dive In',
      dashboardGreetingSuffix: 'The tides are calm tonight.',
      quote: '"The cure for anything is salt water — sweat, tears, or the sea."',
      quoteSource: 'Ocean Depths',
      aiGreeter: "Like the ocean, I'm here — deep, patient, and always moving. What's flowing through you?",
      journalPlaceholder: 'Let your words flow like the tide...',
      noJournalText: 'The ocean page is empty. Cast your first wave.',
      moodTitle: 'Dashboard',
      moodSubtitle: 'What currents are moving through you?',
    },
  },

  'night-sky': {
    id: 'night-sky',
    label: 'Night Sky',
    description: 'Celestial Night',
    icon: '✨',
    swatchGradient: 'linear-gradient(135deg, #1e1b4b, #4c1d95)',
    cssVars: {
      '--background': '#020617',
      '--bg-gradient': 'linear-gradient(135deg, #020617 0%, #0f172a 50%, #1e1b4b 100%)',
      '--foreground': '#f8fafc',
      '--muted': '#94a3b8',
      '--glass-bg': 'rgba(30, 41, 59, 0.45)',
      '--glass-border': 'rgba(255, 255, 255, 0.08)',
      '--primary': '#bac3ff',
      '--secondary': '#a855f7',
      '--primary-glow': 'rgba(139, 92, 246, 0.25)',
      '--canvas-bg': '#05060b',
      '--glass-shadow': '0 20px 50px rgba(0, 0, 0, 0.5)',
    },
    colors: {
      primary: '#bac3ff',
      primaryContainer: '#3c4b9e',
      secondary: '#818cf8',
      accent: '#a855f7',
      foreground: '#f8fafc',
      muted: '#94a3b8',
      glass: 'rgba(30, 41, 59, 0.4)',
      glassBorder: 'rgba(255, 255, 255, 0.05)',
      glow: 'rgba(168, 85, 247, 0.4)',
      surface: '#05060b',
    },
    copy: {
      heroHeadline: 'Find Your\nInner Calm.',
      heroTagline: 'Meet Lumea, your compassionate AI companion. A safe, structured space to talk, track patterns, and breathe better.',
      heroCTA: 'Get Started 🌟',
      dashboardGreetingSuffix: 'Your sanctuary is peaceful',
      quote: '"The moon does not fight the sun to shine. It waits for its time."',
      quoteSource: 'Celestial Guidance',
      aiGreeter: "Hello, stargazer. I'm Lumea — here under the same sky as you. What's on your mind?",
      journalPlaceholder: 'Write under the stars... your thoughts are safe here.',
      noJournalText: 'No reflections yet. Begin writing to fill your celestial archive.',
      moodTitle: 'Mood Galaxy',
      moodSubtitle: 'Your emotional constellations, mapped.',
    },
  },
};

export const DEFAULT_THEME_ID = 'night-sky';

export const THEME_ORDER = ['none', 'dark', 'desert', 'ocean', 'night-sky'];
